### ISSUE TITLE
How-to Docker

### ISSUE THREAD

**Issue by j3r13** [Minims/SomfyProtect2MQTT#133]
Hi,
Thank you for contributing SomfyProtect2MQTT it works very well with HA.

The only thing missing, in my opinion, is a good howto. In particular the explanation of the docker version. Apparently the docker version expects an already present and completed config.yalm and of course a working MQTT installation in Docker. All this is not described in the readme/howto. I would like to write a good howto for the docker version. How can I contribute?

**Comment by Minims** [comment]
Hello,

I provide a Docker but I have never use it. A how-to is welcome.
You fork the repository, Update the Readme file to explain the docker version (or make a new one dedicated to Docker)
Then commit the file, make a PR (Pull request in my repo) and that's all.

**Comment by unsecret** [comment]
Hello, 
I'm experiencing issue to set it up. I figured out the config file and now the docker is starting but i don't manage to configure MQTT on HA in order to connect. I have a connection failure :(

**Comment by Dwarfy27950** [comment]
Hello,
I would be happy to get current version of the document. I achieve to set up a mqtt brocker, started python3 main.py with -c option but there's no entities appearing in home assistant. I don't know what I am doing wrong

**Comment by kahatie** [comment]
Hello 

look at #150 i have little difficult too for install on docker so i write a little guide 

here part of my docker compose if it can help someone 
```
version: "3.8"
services:
  homeassistant:
    image: ghcr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Paris
    ports:
      - 8123:8123
    volumes:
      - /mnt/user/appdata/homeassistant:/config
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --no-check-certificate --spider http://localhost:8123/static/icons/favicon.ico
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    expose:
      - 1883
    volumes:
      - /mnt/user/appdata/mosquitto/config:/mosquitto/config
      - /mnt/user/appdata/mosquitto/data:/mosquitto/data
      - /mnt/user/appdata/mosquitto/log:/mosquitto/log
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-p", "1880", "-t", "$$SYS/#", "-C", "1", "-i", "healthcheck", "-W", "3"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
  somfyprotect2mqtt:
    image: minims/somfyprotect2mqtt
    container_name: SomfyProtect2mqtt
    depends_on:
      - mosquitto
    volumes:
      - /mnt/user/appdata/somfyprotect2mqtt:/config 
```
