### ISSUE TITLE
get the alarm alert status

### ISSUE THREAD

**Issue by yozart** [Minims/SomfyProtect2MQTT#159]
Hello guys,
Pretty new to HA, I'm also using nodered which is very visual.
When my alarm is yelling, I wanted to send an alert through home assistant to my phone. I can't find a way of doing it :/ might be dumb question, sorry, but didn't find anything in the how-to / forum / the web on how to perform it. Kind regards

**Comment by Minims** [comment]
Hello, 

I don't know how nodered works, but must work in HA automation:

```
description: "Notify on Alarm Triggered"
mode: single
trigger:
  - platform: state
    entity_id:
      - alarm_control_panel.somfy_home_alarm_maison
    to: triggered
condition: []
action:
  - service: notify.mobile_app_***
    metadata: {}
    data:
      title: Alarm
      message: Alarm is Triggered !!
```
