### ISSUE TITLE
snapshot not available

### ISSUE THREAD

**Issue by gmarchett** [Minims/SomfyProtect2MQTT#17]
Ciao, thanks a lot for your job! I've integrated this module and it works fine (i  can activate alarm, siren, etc.), but if I try to see a snapshot from the camera in a Glance card, i receive a grey (or broken) image. Did it never happened to you?
<img width="754" alt="Schermata 2021-09-28 alle 13 20 40" src="https://user-images.githubusercontent.com/60212675/135077452-249b0ebf-a499-412a-8ed2-213e702d9696.png">
Thanks for your support

PS
If you add the streaming support, you update your level to God :-)

**Comment by Minims** [comment]
Hello,

I have never had this issue. My camera is setup like this in Lovelace.
As I know, It need that your camera was with shutter on at least 1min to get a snapshot.

If you still have the issue, can you check with MQTT explorer that the camera have a picture in the data received ? 

```
type: picture-glance
entities:
  - entity: switch.indoor_camera_shutter_state
  - entity: sensor.indoor_camera_wifi_level_percent
  - entity: device_tracker.somfy_indoor_camera
camera_image: camera.indoor_camera_snapshot
title: Home
```

I don't think I will be able to make streaming working. It might be possible, but I have not the knowledge in video streaming to add it.
