### ISSUE TITLE
Managin two installation in Somfy like home and garage not colocated

### ISSUE THREAD

**Issue by paquitoloco** [Minims/SomfyProtect2MQTT#171]
Hi, bonjour Minims,

I have two location assigned to my Somfy account and i'd like to control both of them in the same HA. Is it possible to do so?

Thanks!

**Comment by Minims** [comment]
Hello,

Yes, just define both site label in config : 

```
---
# Somfy Protect APP credentials
somfy_protect:
  username: "email@address.com"
  password: "********"

  # Zones Label to check
  sites:
    - Maison
    - "Maison 2"

```
