### ISSUE TITLE
La fonction trigger ne fonctionne pas 

### ISSUE THREAD

**Issue by Sakulq** [Minims/SomfyProtect2MQTT#56]
Bonjour,

Un grand merci pour ton travail, désolé de ne pas poster en anglais, ce n'est pas mon fort.

J'ai créé un script pour associer des détecteurs de mouvement zigbee au declenchement de mon alarme, mais la fonction trigger ne fonctionne pas. Si dans le script je remplace par arm ou disarm le script fonctionne pas. Aurais tu une idée ? Quand je lis les logs il me met "cant reach item"
Si tu as besoin de ma renseignement sur ma configuration n'hésite pas.

Cordialement

**Comment by Minims** [comment]
Hello,

Pas de soucis je pense que cette alarme est utilisé majoritairement par des francophones :-)


> Si dans le script je remplace par arm ou disarm le script fonctionne pas
Tu veux ca fonctionne dans ce cas, mais pas avec le trigger ? 

Tu sais me partager ton script ?

Si tu veux déclencher la sirène je pense tu dois appeler : switch.<site>_siren

**Comment by Sakulq** [comment]
Salut,

J'utilise ce script du coup 

```
id: '1662664255424'
alias: Déclenchement alarme sur détections mouvement
description: ''
trigger:
  - type: motion
    platform: device
    device_id: a538c75bfc710737b2b940b601a0b4cd
    entity_id: binary_sensor.detecteur_de_mouvements
    domain: binary_sensor
  - type: motion
    platform: device
    device_id: 96362e0b968f665cec0295ae432489dc
    entity_id: binary_sensor.detecteur_de_mouvements_2
    domain: binary_sensor
  - type: motion
    platform: device
    device_id: f65ad541a8c44c5949246d5f859357db
    entity_id: binary_sensor.detecteur_de_mouvements_3
    domain: binary_sensor
  - type: motion
    platform: device
    device_id: 370199341c470d30a6755d48bd06d1fb
    entity_id: binary_sensor.detecteur_de_mouvements_4
    domain: binary_sensor
  - type: motion
    platform: device
    device_id: bdbafb38ff44b5571b1fd425bad611a3
    entity_id: binary_sensor.detecteur_de_mouvements_5
    domain: binary_sensor
  - type: motion
    platform: device
    device_id: 7ddfe838731f636a73ad21114bb2aac0
    entity_id: binary_sensor.detecteur_de_mouvements_6
    domain: binary_sensor
  - type: turned_on
    platform: device
    device_id: d0ab00a2e1976354b49994e8cc7a453e
    entity_id: binary_sensor.meuble_noir_motion_sensor
    domain: binary_sensor
  - type: turned_on
    platform: device
    device_id: eb2ea49b0b154d0a48e990c3a12db78e
    entity_id: binary_sensor.meuble_gris_motion_sensor
    domain: binary_sensor
condition:
  - condition: device
    device_id: 0fac0dc2fe3271088b5709aca9a1a037
    domain: alarm_control_panel
    entity_id: alarm_control_panel.maison
    type: is_armed_away
action:
  - service: media_player.play_media
    target:
      entity_id: media_player.enceinte_salon
    data:
      media_content_id: >-
        media-source://media_source/local/HMNHart_Battements de coeur (ID
        0218)_LS.mp3
      media_content_type: audio/mpeg
    metadata:
      title: HMNHart_Battements de coeur (ID 0218)_LS.mp3
      thumbnail: null
      media_class: music
      children_media_class: null
      navigateIds:
        - {}
        - media_content_type: app
          media_content_id: media-source://media_source
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: switch.toggle
    data: {}
mode: single
```
